server:
  port: 8080
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging: # 配置日志级别，让hibernate打印执行sql
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
# spring boot actuator配置可以在info接口中显示的信息
info:
  app:
    name: microservice-provider-user
    encoding: UTF-8
    java:
      source: 1.8.0_151
      target: 1.8.0_151
