spring:
  application:
    name: microservice-discovery-eureka-ha

---
# profile peer1
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名是peer1
  client:
    service-url:
      default-zone: http://peer2:8762/eureka/ # 将自己注册道peer2这个eureka上

---
# profile peer2
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/