#通过bootstrap.yml获取config server上的配置
#spring:
#  application:
#    name: order
#  datasource:
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true # 打开jpa的sql显示
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
spring:
  redis:
    host: localhost
    port: 6379