service:
  name: user-thrift-service
  port: 7911
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver